# Numpy
- 수치 연산에 최적화 된 파이썬 라이브러리
- 대량의 숫자 데이터를 빠르고 효율적으로 처리하기 위해 사용

## ndrrary (다차원 배열)
- 다차원 배열의 타입으로 데이터를 효율적으로 처리
    - 같은 타입의 데이터만 담음
    - 여러 차원으러 확장 가능 (1차원,2차원,3차원 등)
    - 한 번에 연산 가능(반복문 사용하는 list 대비 훨씬 빠름)

In [2]:
# 과례적으로 np라는 별칭 사용
import numpy as np
np.__version__

'2.4.3'

In [3]:
# python list를 ndrrary로 생성
# 1차원
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
# 2차원
arr2 = np.array([[1,2,3],[4,5,6]])
# 각 차원의 길이가 정확하게 일치해야 한다
# arr2 = np.array([[1,2,3],[4,5]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# list 와 ndarrary의 타입과 값 비교
print(type([1,2,3]),[1,2,3])
print(type(arr),arr)

<class 'list'> [1, 2, 3]
<class 'numpy.ndarray'> [1 2 3]


## ndarray 속성
- shape : 배열의 형태
- ndim : 베열의 차원 수
- size : 전체 요소 수
- dtype : 요소의 자료형

## dtype
dtype은 배열 요소의 자료형을 의미한다. 자주 보게 되는 자료형은 아래와 같다.
- 정수형 : int32,int64
- 실수형 : float21, float64
- 부리언형 : bool
- 문자열형 : 문자열 또는 유니코드 문자열

In [9]:
print(arr)
print(arr2)
print(arr.shape, arr2.shape)
print(arr.ndim, arr2.ndim)
print(arr.size, arr2.size)
print(arr.dtype, arr2.dtype)

[1 2 3]
[[1 2 3]
 [4 5 6]]
(3,) (2, 3)
1 2
3 6
int64 int64


In [11]:
# 실수형 ndarray 생성
arr3 = np.array([
    [1.23,3.45],
    [5.67,7.89],
    [12.34,23.45]
])
print(arr3)
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)
print(arr3.dtype)

[[ 1.23  3.45]
 [ 5.67  7.89]
 [12.34 23.45]]
(3, 2)
2
6
float64


In [ ]:
# dtype 지정
arr4 = np.array([
    [1.23,3.45],
    [5.67,7.89],
    [12.34,23.45]
],dtype=int)
print(arr4.dtype,arr4)

arr5 = np.array([1,0,1,0],dtype=bool)
print(arr5.dtype,arr5)

# astype() : 생성 후 자료형 변환
arr6 = np.array([
    [1.23,3.45],
    [5.67,7.89],
    [12.34,23.45]
])
new_arr = arr6.astype(int)      # dtype을 int로 변환, 원본 변경하지 않고 새로운 배열 변환
print(new_arr.dtype,new_arr)
print(arr6.dtype,arr6)

int64 [[ 1  3]
 [ 5  7]
 [12 23]]
bool [ True False  True False]
int64 [[ 1  3]
 [ 5  7]
 [12 23]]
float64 [[ 1.23  3.45]
 [ 5.67  7.89]
 [12.34 23.45]]


In [ ]:
# ndarray는 하나으 타입만 요소로 가질 수 있다.
arr = np.array([1,2,3,'hi'])
print(arr)
print(arr.dtype)        # 유니코드 방식의 문자열 타입으로 변경 됨

['1' '2' '3' 'hi']
<U21


## 특정 형식의 ndarray 생성하기
원하는 값으로 채워진 배열을 만들 수 있다.
- np.zeros() : 0으로 채운 배열 생성
- np.ones() : 1로 채운 배열 생성
- np.fulls() : 지정 값으로 채운 배열 생성

In [ ]:
# np.zeros(shape : tuple)
arr1 = np.zeros((3,2),dtype=float)      # dtype = float가 기본 값
print(arr1)
arr2 = np.zeros([3,2],dtype=int)
print(arr2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0 0]
 [0 0]
 [0 0]]


In [22]:
# np.ones(shape)
arr3 = np.ones((3,2))
print(arr3)

# np.full(shape,n)
arr4 = np.full((4,3),3)
print(arr4)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]


- np.zeors_like() : 기존 배열과 같은 shape의 0배열 생성
- np.ones_like() : 기존 배열과 같은 shape의 1배열 생성
- np.full_like() : 기존 배열과 같은 shape의 지정 값 배열 생성

In [23]:
data = np.array([[1,2,3],[4,5,6]]) # shape => (2,3)

arr5 = np.zeros_like(data)
print(arr5)

arr6 = np.ones_like(data)
print(arr6)

arr7 = np.full_like(data,7)
print(arr7)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[7 7 7]
 [7 7 7]]


## 특정 범위의 ndarrary 생성하기
일정한 규칙을 가진 숫자 배열을 만들 수 있다.
- np.arange() : 일정 간격의 값 생성
- np.linespace() : 구간을 동일한 개수로 나누어 생성
- np.logspace() : 로그 간격으로 값 생성

In [24]:
# np.arange(start,end,step)
arr1 = np.arange(0,10)      # step = 1 default
print(arr1)

arr2 = np.arange(0,10,2)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [28]:
# np.linespace(start,end,len) : start-end(포함)까지 len개의 균등간격 ndarrary 반환
arr3 = np.linspace(0,10,10)
print(arr3)

arr4 = np.linspace(0,10,11)
print(arr4)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
# np.logspace(start,end,len,base) : start부터 end까지 len개의 숫자를 지수로 하는 base 거듭제곱
arr5 = np.logspace(1,10,10,base=2)
print(arr5)

arr6 = np.logspace(1,10,10)     # base = 10이 default
print(arr6)
# 1.e+01 : (가수부)e(지수부)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]
