# 통계 기초
Numpy 통계는 정식 통계분석 도구라기보다, 데이터를 빠르게 요약하고 분포를 감 잡기 위한 기초 연산이다.

In [1]:
import numpy as np

## 중심 경향 축도(Central Tendency)
데이터의 대표적인 중심 값을 나타내는 통꼐 지표이다.
대표적으로 다음 세가지를 많이 사용한다.
- 평균(mean) : 모든 값의 합을 데이터의 개수로 나눈 값
- 중앙값(median) : 데이터를 정렬했을때 가운데 위치한 값
- 최빈값(mode) : 가장 많이 등장하는 값

In [2]:
# 학생들의 시험점수
scores = np.array([85, 90, 92, 88, 90, 75, 88, 95, 92, 85, 80, 95, 100, 92, 85])

In [ ]:
# 평균(Mean) : 데이터의 전체적인 중심을 나타내는 가장 기본적인 통계값
print(f'합계 : {np.sum(scores)}')
print(f'데이터 개수 : {scores.size}')
print(f'평균 : {np.mean(scores)}')

합계 : 1332
데이터 개수 : 15
평균 : 88.8


In [5]:
# 중앙값(median) : 데이터를 정렬했을때 가운데 위치한 값
# 홀수 -> 가운데 1개 값
# 짝수 -> 가운데 2개 값의 평균
# 이상치(outlier)의 영향을 평균보다 덜 받는 특징
print(sorted(scores))
print(f'중앙값 : {np.median(scores)}')

[np.int64(75), np.int64(80), np.int64(85), np.int64(85), np.int64(85), np.int64(88), np.int64(88), np.int64(90), np.int64(90), np.int64(92), np.int64(92), np.int64(92), np.int64(95), np.int64(95), np.int64(100)]
중앙값 : 90.0


In [ ]:
# 최빈값(mode) : 데이터에서 가장 많이 등장하는 값
print(f'중복 제거한 값 : {np.unique(scores)}')
values, counts = np.unique(scores,return_counts=True)
print(values,counts)

max_count = np.max(counts)
# 최대 빈도수와 같은 위치의 값만 선택
vals = values[counts==max_count]
print(f'최빈값 : {vals}, 빈도 수 : {max_count}')

중복 제거한 값 : [ 75  80  85  88  90  92  95 100]
[ 75  80  85  88  90  92  95 100] [1 1 3 2 2 3 2 1]
최빈값 : [85 92], 빈도 수 : 3


## 산포 측도
데이터가 평균을 기준으로 얼마나 퍼졌 있는지를 나타내는 지표이다.
대표적으로 다음 두 가지를 많이 사용한다.
- 분산(varience)
- 표준편차(standard deviation)

In [8]:
# 분산 : 데이터가 평균에서 얼마나 떨어져 있는지 나타내는 값
# 값이 클수록 데이터의 퍼짐 정도가 크다는 의미
# (값 - 평균)^2의 평균
print(f'분산 : {np.mean((scores - np.mean(scores))**2)}')
print(f'분산 : {np.var(scores)}')

분산 : 36.559999999999995
분산 : 36.559999999999995


In [ ]:
# 표준 편차 : 분산의 제곱근
# 데이터가 평균에서 멀마나 퍼져 있는지를 직관적으로 나타냄
print(f'표준편차 : {np.sqrt(np.var(scores))}')
print(f'표준편차 : {np.std(scores)}')

표준편차 : 6.046486583132389
표준편차 : 6.046486583132389


## 모집단 VS 표본
분산과 표준편차는 계산 방식에 따라 두 가지가 있다.
- 모집단 : 던체 데이터를 알고 있을 때
- 표본: 일부 데이터로 전체를 추정할 때

Numpy에서는 ddof 옵션으로 구분한다. (분산 계산 시 나누는 값을 조정)
- ddof = 0 : 모집단(default)
- ddof = 1 : 표본

In [ ]:
# 모집단 기준 계산
print(f'모집단 분산 : {np.var(scores,ddof=0)}')
print(f'모집단 표준편차 : {np.std(scores,ddof=0)}')
# 표본 기준 계산 (분산 계산 시 나누는 값을 n-1로 처리하므로 값이 약간 크게 나온다.)
print(f'표본 분산 : {np.var(scores,ddof=1)}')
print(f'표본 표준편차 : {np.std(scores,ddof=1)}')

모집단 분산 : 36.559999999999995
모집단 표준편차 : 6.046486583132389
표본 분산 : 39.17142857142857
표본 표준편차 : 6.258708219067939


## 자주 상용하는 기본 통계 함수
Numpy는 데이터의 기본적인 통계 정보를 빠르게 확인 할 수 있는 함수를 제공한다.
이 함수들은 데이터 탐색(EDA)이나 간단한 통계 확인에서 자주 사용 된다.

In [ ]:
# 예시 데이터
values = np.array([12,25,8,45,33,17,29,41])

# 합계, 최대, 최소
print(np.sum(values))
print(np.min(values))
print(np.max(values))

# 최대값, 최소값의 위치
print(np.argmin(values))
print(np.argmax(values))

# 범위 : 데이터의 전체 퍼짐 정도 (max - min)
print(np.ptp(values))

210
8
45
2
3
37


## 난수 생성 (random data)
Numpy는 다양한 확률 분포 기반의 난수 생성 함수를 제공한다.
대표적으로 다음 분포를 많이 사용한다.
- 정규분포(normal distribution)
- 균등분포(uniform distribution)

데이터 시뮬레이션이나 테스트 데이터 생성에 사용된다.

### 정규 분포
평균을 중심으로 좌우 대칭인 종 모양 분포이다.
Numpy에서는 np.random.normal() 함수로 생성한다.

In [ ]:
# random.normal(loc,scale,size)
# loc : 평균값, scale : 표준편차, size : 개수
arr = np.random.normal(0,1,100)
arr = np.random.normal(0,1,(10,10))
arr

array([[ 2.79014015, -0.20197793,  1.84034377, -0.96828756,  0.02882839,
         0.4352574 , -0.63072389, -0.72432137, -1.51949578, -0.32404681],
       [-0.69556181,  0.63519632, -3.26818075,  0.67750622,  0.93062392,
         1.67523606, -0.22840204,  0.58126792,  2.39735647, -0.7517641 ],
       [-0.8302142 ,  0.19390721,  0.18408126, -0.93096083,  0.3595482 ,
        -0.04944393,  0.61806627, -0.97003843,  0.18232963, -0.78246392],
       [-1.19009411, -0.55228276, -0.12681423, -0.60174093, -0.35077761,
         0.19393841,  0.52198235, -0.71617686,  0.88135431,  0.68342159],
       [-1.35885395, -0.17948006,  1.68907492, -0.73753257, -0.31887893,
        -0.23432327, -0.38624042, -0.79220299, -0.69400119, -1.61717043],
       [-0.01381901,  1.15553094, -0.73872197, -0.46583362, -1.26164123,
         2.2158038 ,  0.60482723, -1.91125587,  0.38533884, -0.2041922 ],
       [-0.89636569,  1.21167331, -0.76272732, -1.65032671,  0.91053015,
        -1.07282017,  0.31978579,  1.08318827

### 표준 정규 분포
np.random.randn()은 평균 0, 표준편차 1의 정규분포 데이터를 생성한다.

In [19]:
arr = np.random.randn(100)
arr = np.random.randn(5,20)
arr

array([[-4.66561737e-01,  2.25242204e-01,  1.05343632e+00,
         4.63210396e-02, -3.93119538e-02,  1.19694262e+00,
        -2.42559825e-01,  1.94197808e+00, -1.22591756e+00,
        -8.86214582e-01, -1.66058562e+00, -3.70190912e-01,
         3.07041599e-01, -4.81727189e-01, -1.41268512e+00,
         4.32036245e-02,  4.57815050e-01, -1.08385503e+00,
        -1.31898359e+00,  9.80513099e-01],
       [ 4.47707324e-02, -8.82592281e-01, -1.06359882e+00,
         7.60690195e-01, -1.10553769e+00,  8.05721265e-01,
         6.29870770e-01, -6.40536479e-01, -1.59136151e+00,
        -3.25971113e-01,  7.25407334e-01,  1.65849846e+00,
         2.01189757e+00, -4.62205201e-01, -1.10747542e+00,
         1.84996015e-01,  1.56178546e-01,  7.37486110e-01,
         3.74010768e-01,  8.40778366e-01],
       [ 1.77220983e-01,  6.04993910e-01,  1.47387962e+00,
         2.10824306e-01,  6.62257425e-01, -5.04268265e-01,
         9.99474612e-01, -2.45558072e+00,  1.48903345e+00,
        -6.21786685e-01, -7.0

## 균등 분포
모든 값이 동일한 확률로 발생하는 분포이다.
np.random.randint() : 지정한 범위에서 정수 난수를 생성한다.

In [ ]:
# random.randint(low, high, size)
# low~high 범위의 size 개수 균등 분포 반환
arr = np.random.randint(1,100,1000)
arr

array([13, 31, 72, 90,  7, 32, 12, 26, 54, 12, 45, 78, 66, 99, 45, 61, 24,
       84, 79, 60, 55, 87, 56, 54, 53, 34,  1, 48, 76, 37, 44, 34, 21,  8,
       59, 31,  1, 36, 31, 24, 60,  6, 26, 24,  3, 24, 93, 24, 92, 43, 15,
       39, 26,  3, 43, 44,  8,  5, 20, 56, 81, 42, 37, 57, 97,  5, 83, 36,
       85, 61, 13, 69, 14, 50, 98, 32, 11, 16, 26, 25, 39, 37, 31, 71, 16,
       32, 75, 55, 89, 99, 42, 75, 80, 25, 46, 92, 52,  9, 86, 14, 83, 34,
       61, 53, 89, 89, 12, 55, 44, 87, 73, 18, 30, 43, 46, 91, 29, 71, 27,
       56, 75, 45, 54, 11, 48, 17, 58, 33, 61, 56, 59, 48, 18, 41, 69,  6,
        1, 71, 81, 59, 32, 54, 79, 54, 14, 58, 93,  5, 17,  8, 46, 92, 18,
       78, 76, 68, 42, 33, 90, 46, 18, 24, 13, 96, 40,  6, 49, 17, 62, 79,
       23, 58, 82, 82, 21, 39, 33, 10, 75, 94, 60, 28, 15, 58, 18, 13, 97,
       76, 23, 17, 10, 56, 87, 68, 10, 40, 40,  9, 28, 42, 98, 99, 91, 63,
       86, 17, 81, 44, 79, 76,  3, 46, 68,  6, 43, 69, 97, 28, 12, 20, 19,
       18, 78, 12, 35, 66

### np.random.rand() : 0~1 사이의 균등분포 실수 난수를 생성한다.

In [21]:
arr = np.random.rand(10,10)
arr

array([[0.39054325, 0.22419284, 0.66474923, 0.67530751, 0.75568437,
        0.1417684 , 0.1006257 , 0.44548987, 0.71672305, 0.71187499],
       [0.80477671, 0.27333125, 0.24726731, 0.07000341, 0.78378643,
        0.57981259, 0.49598834, 0.1421459 , 0.91346256, 0.06207907],
       [0.08635964, 0.47157593, 0.80332101, 0.48525026, 0.52001989,
        0.14546802, 0.9413693 , 0.90580368, 0.26881751, 0.16531278],
       [0.61520631, 0.20119723, 0.63627759, 0.13696888, 0.18876   ,
        0.9499607 , 0.27803167, 0.88513047, 0.89986883, 0.53953086],
       [0.11595065, 0.275961  , 0.36226169, 0.36651282, 0.94093274,
        0.01864761, 0.59872783, 0.59787536, 0.89794925, 0.58040817],
       [0.86194659, 0.16226975, 0.79291682, 0.85066321, 0.36123479,
        0.02965319, 0.21270981, 0.99988973, 0.80561258, 0.58659667],
       [0.31211616, 0.48599408, 0.19740146, 0.90961987, 0.27844373,
        0.42688301, 0.07644511, 0.77507532, 0.72656572, 0.29771082],
       [0.20002893, 0.7601963 , 0.0625092

## seed
난수 생성의 재현성을 위해 seed 값을 고정할 수 있다.

In [33]:
np.random.seed(0)
np.random.rand(2,3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

## 샘플링
np.random.choice() 는 기존 데이터에서 무작위로 값을 선택할때 사용한다.
옵션
- replace = True : 복원 추출
- replace = False : 비복원 추출

In [ ]:
arr = np.array([10,3,5,7,8,9])
np.random.choice(arr)                           # 1개 추출
np.random.choice(arr,size=3)                    # 추출 개수 설정
np.random.choice(arr,size=3,replace=False)      # 중복 불허 비복원 추출

array([5, 7, 9])

In [87]:
# 확률 지정
probs = [0.8,0.05,0.05,0.05,0.025,0.025]
np.random.choice(arr,p=probs)

np.int64(10)