# 병합/분리
배열의 요소를 추가하거나 삭제할 수 있고, 여러 배열을 하나로 합치거나 하나의 배열을 여러개로 나눌 수 있다.

In [1]:
import numpy as np

## 요소 삽입/삭제
'np.insert()' : 지정한 위치에 새로운 값을 삽입한다.

In [4]:
arr = np.arange(1,13).reshape(3,4)
print(arr)

# insert(ndarray, idex, elems, axis)
print(np.insert(arr,1,[50,50,50,50],axis=0))
print(np.insert(arr,1,[50],axis=0))     # 브로드캐스팅 연산 처리
print(np.insert(arr,1,50,axis=0))     # 브로드캐스팅 연산 처리

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [50 50 50 50]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [50 50 50 50]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [50 50 50 50]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
# axis=1 열 단위 추가
print(np.insert(arr,1,[50,50,50],axis=1))
print(np.insert(arr,1,[50],axis=1))
print(np.insert(arr,1,50,axis=1))

[[ 1 50  2  3  4]
 [ 5 50  6  7  8]
 [ 9 50 10 11 12]]
[[ 1 50  2  3  4]
 [ 5 50  6  7  8]
 [ 9 50 10 11 12]]
[[ 1 50  2  3  4]
 [ 5 50  6  7  8]
 [ 9 50 10 11 12]]


## np.delete()
지정한 위치의 행, 열 또는 요소를 삭제한다.

In [10]:
arr = np.arange(1,13).reshape(3,4)
print(arr)

# 특정 행 삭제
print(np.delete(arr,1,axis=0))

# 특정 열 삭제
print(np.delete(arr,1,axis=1))

# None : 1차원 배열로 펼쳐서 동작
print(np.delete(arr,1,axis=None))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]]
[ 1  3  4  5  6  7  8  9 10 11 12]


## 병합
여러 배열을 하나의 배열로 합치는 방법이다.

### np.append()
배열 뒤에 값을 추가한다. 

In [11]:
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
print(np.append(arr1,arr2))
print(np.append(arr1,arr2,axis=None))   # 기본 값 None

print(np.append(arr1,arr2,axis=0))  # (2,3) (2,3) => (4,3)
print(np.append(arr1,arr2,axis=1))  # (2,3) (2,3) => (2,6)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## np.vstack() : vertical stack -> 세로로 쌓기
배열을 세로 방향으로 병합한다.
즉 행 방향(axis=0)으로 이어 붙인다.
따라서 병합하려는 배열들의 열 수가 같아야 한다.

## np.hstack() : horizontal stack -> 가로로 쌓기
배열을 가로 방향으로 병합한다.
즉 행 방향(axis=1)으로 이어 붙인다.
따라서 병합하려는 배열들의 행 수가 같아야 한다.

In [15]:
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)
print(arr1)
print(arr2)

print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## np.concatenate()
지정한 축을 기준으로 배열을 병합하는 가장 일반적인 함수이다.

In [16]:
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)
print(arr1)
print(arr2)

print(np.concatenate((arr1,arr2),axis=0))
print(np.concatenate((arr1,arr2),axis=1))
print(np.concatenate((arr1,arr2),axis=None))

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## np.column_stack()
1차원 배열들을 열 단위로 묶어서 2차원 배열로 만든다.
이미 2차원 배열인 경우에는 hstack() 또는 concatenate(axis=1)과 유사하게 동작한다.

In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.column_stack((a,b)))

[[1 4]
 [2 5]
 [3 6]]


## 분할
하나의 배열을 여러 개의 배열로 나누는 방법이다.
행 기준 분할과 열 기준 분할이 있다.

### no.vsplit()
배열을 세로 방향으로 분할한다. 즉 행 기준(axis=0)으로 여러 배열로 나눈다.
행 개수가 나누는 수로 균등하게 나누어 떨어져야 한다.

### no.hsplit()
배열을 가로 방향으로 분할한다. 즉 열 기준(axis=1)으로 여러 배열로 나눈다.
열 개수가 나누는 수로 균등하게 나누어 떨어져야 한다.

In [22]:
arr = np.arange(1,25).reshape(6,4)
print(arr)

# 6행이므로 6의 약수로 분할 -> (6,3,2,1)
print(np.vsplit(arr,6))
# print(np.vsplit(arr,4)) -> 오류 발생

# 4열이므로 4의 약수로 분할 -> (4,2,1)
print(np.hsplit(arr,2))
# print(np.hsplit(arr,3)) -> 오류 발생

# 인덱스 기준 분할
print(np.hsplit(arr,[1,3]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]]), array([[17, 18, 19, 20]]), array([[21, 22, 23, 24]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])]
[array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]]), array([[ 4],
       [ 8],
       [12],
       [16],
       [20],
       [24]])]
