# numpy_practice2

편의점 판매 데이터를 NumPy로 다루는 실습이다.

범위:
- 05_sort
- 06_merge_split
- 07_reshape

규칙:
- 각 문제 아래 코드 셀에서 직접 풀이
- 필요한 경우 셀 추가 가능
- 배열의 shape를 함께 확인하는 습관을 가지기

## 0. 시작 데이터

In [37]:
import numpy as np

# 3개 지점, 6개 상품의 재고 수량
stock = np.array([
    [12,  5, 18,  7, 10, 15],
    [ 8, 14, 11,  9,  6, 13],
    [16, 10,  9, 12, 14,  8]
])

# 상품 코드
product_ids = np.array([101, 102, 103, 104, 105, 106])

stock

array([[12,  5, 18,  7, 10, 15],
       [ 8, 14, 11,  9,  6, 13],
       [16, 10,  9, 12, 14,  8]])

## 1. 정렬
1) product_ids를 오름차순 정렬하시오.
2) 첫 번째 지점 재고를 오름차순 정렬하시오.
3) stock를 행 기준으로 정렬하시오.

In [78]:
# 여기에 작성
print(np.sort(product_ids))
print(np.sort(stock[0]))
print(np.sort(stock,axis=1))

[101 102 103 104 105 106]
[ 5  7 10 12 15 18]
[[ 5  7 10 12 15 18]
 [ 6  8  9 11 13 14]
 [ 8  9 10 12 14 16]]


## 2. 역순 정렬
두 번째 지점 재고를 내림차순으로 정렬하시오.

In [17]:
# 여기에 작성
print(np.sort(stock[1])[::-1])

[14 13 11  9  8  6]


## 3. argsort
세 번째 지점 재고를 많이 가진 상품 순서의 인덱스를 구하시오.
그리고 그 인덱스를 이용해 상품 코드도 같은 순서로 정렬하시오.

In [18]:
# 여기에 작성
stock_indies = np.argsort(stock[2])[::-1]
print(stock_indies)

print(product_ids[stock_indies])

[0 4 3 1 2 5]
[101 105 104 102 103 106]


## 4. insert
첫 번째 지점 재고 앞에 신상품 재고 20을 삽입한 1차원 배열을 만드시오.

In [19]:
# 여기에 작성
print(np.insert(stock[0],0,20))

[20 12  5 18  7 10 15]


## 5. delete
1) stock에서 마지막 상품 열을 삭제하시오.
2) stock에서 두 번째 지점 행을 삭제하시오.

In [28]:
# 여기에 작성
print(np.delete(stock,-1,axis=1))
print(np.delete(stock,1,axis=0))

[[12  5 18  7 10]
 [ 8 14 11  9  6]
 [16 10  9 12 14]]
[[12  5 18  7 10 15]
 [16 10  9 12 14  8]]


## 6. append / concatenate
아래 online_stock을 stock 뒤에 세로로 붙인 result_append를 만드시오.

In [79]:
online_stock = np.array([[20, 18, 15, 10, 12, 17]])

# 여기에 작성
result_append = np.append(stock,online_stock,axis=0)
print(result_append)

[[12  5 18  7 10 15]
 [ 8 14 11  9  6 13]
 [16 10  9 12 14  8]
 [20 18 15 10 12 17]]


## 7. vstack / hstack
1) stock 아래에 warehouse_stock을 세로로 붙이시오.
2) stock 오른쪽에 event_stock을 가로로 붙이시오.

In [40]:
warehouse_stock = np.array([[30, 25, 28, 20, 26, 22]])
event_stock = np.array([[1], [2], [3]])

# 여기에 작성
print(np.vstack((stock,warehouse_stock)))
print(np.hstack((stock,event_stock)))

[[12  5 18  7 10 15]
 [ 8 14 11  9  6 13]
 [16 10  9 12 14  8]
 [30 25 28 20 26 22]]
[[12  5 18  7 10 15  1]
 [ 8 14 11  9  6 13  2]
 [16 10  9 12 14  8  3]]


## 8. split
product_ids를 3개씩 나누시오.
그리고 stock를 열 기준으로 2개 블록으로 나누시오.

In [46]:
# 여기에 작성
print(np.split(product_ids,2))
print(np.split(stock,2,axis=1))

[array([101, 102, 103]), array([104, 105, 106])]
[array([[12,  5, 18],
       [ 8, 14, 11],
       [16, 10,  9]]), array([[ 7, 10, 15],
       [ 9,  6, 13],
       [12, 14,  8]])]


## 9. reshape
1) 0부터 23까지의 값을 가지는 배열 arr를 만드시오.
2) arr를 4 x 6으로 바꾸시오.
3) arr를 2 x 3 x 4로 바꾸시오.

In [48]:
# 여기에 작성
arr = np.arange(0,24)
print(arr.reshape(4,6))
print(arr.reshape(2,3,4))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## 10. -1 활용 reshape
arr를 이용해
1) 6행으로 reshape
2) 마지막 차원을 2로 갖도록 reshape
를 수행하시오.

In [52]:
# 여기에 작성
print(arr.reshape(6,-1))
print(arr.reshape(-1,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


## 11. ravel / flatten
matrix를 1차원으로 펼쳐서
1) ravel 결과
2) flatten 결과
를 각각 확인하시오.

In [53]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 여기에 작성
print(matrix.ravel())
print(matrix.flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


## 12. expand_dims / squeeze
1) product_ids에 axis=0 축을 추가하시오.
2) product_ids에 axis=1 축을 추가하시오.
3) 추가한 축을 다시 제거하시오.

In [58]:
# 여기에 작성
print(np.expand_dims(product_ids,axis=0))
print(np.expand_dims(product_ids,axis=1))
print(np.expand_dims(product_ids,axis=1).squeeze())

[[101 102 103 104 105 106]]
[[101]
 [102]
 [103]
 [104]
 [105]
 [106]]
[101 102 103 104 105 106]


## 13. transpose
stock의 행과 열을 바꾼 배열을 만드시오.

In [59]:
# 여기에 작성
print(stock.T)

[[12  8 16]
 [ 5 14 10]
 [18 11  9]
 [ 7  9 12]
 [10  6 14]
 [15 13  8]]


## 14. 종합 문제
아래 daily_stock은 2개 지점의 3일치, 4개 상품 재고이다.
shape는 (2, 3, 4) 이다.
1) 하루 단위로 보기 쉽게 6 x 4 형태로 reshape 하시오.
2) 각 행의 재고 합계를 구하시오.
3) 재고 합계가 작은 순서대로 행 인덱스를 구하시오.
4) 가장 재고 합계가 작은 하루의 데이터만 선택하시오.

In [77]:
daily_stock = np.array([
    [[10, 12,  8,  9],
     [11, 13,  7, 10],
     [ 9, 14,  8, 11]],

    [[15, 10, 12, 13],
     [14, 11, 10, 12],
     [13,  9, 11, 10]]
])

# 여기에 작성
day_stock = daily_stock.reshape(1,6,4).squeeze()
print(day_stock)

print(day_stock.sum(axis=1))
print(np.argsort(day_stock.sum(axis=1)))
print(day_stock[np.argsort(day_stock.sum(axis=1)).min()])

[[10 12  8  9]
 [11 13  7 10]
 [ 9 14  8 11]
 [15 10 12 13]
 [14 11 10 12]
 [13  9 11 10]]
[39 41 42 50 47 43]
[0 1 2 5 4 3]
[10 12  8  9]
